FROM tomcat:9-jdk11

WORKDIR /usr/local/tomcat
COPY tomcat-users.xml /usr/local/tomcat/conf/
COPY settings.xml /usr/local/tomcat/conf/
RUN rm -rf webapps/*
COPY manufacturer-webapp*.war /usr/local/tomcat/webapps/ROOT.war
CMD ["catalina.sh", "run"]

