#!/bin/bash

# Sample script that parses the given voucher and displays the device UUID in it.

usage() {
    exitCode=${1:-0}
    cat << EndOfMessage
Usage: ${0##*/} <voucher-file>
EndOfMessage
    exit $exitCode
}

if [[ -z $1 || $1 == '-h' || $1 == '--help' ]]; then usage 0; fi

voucherFile=$1

# Check the exit code passed in and exit if non-zero
chk() {
    local exitCode=$1
    local task=$2
    local dontExit=$3   # set to 'continue' to not exit for this error
    if [[ $1 == 0 ]]; then return; fi
    echo "Error: exit code $exitCode from: $task"
    if [[ $dontExit != 'continue' ]]; then
        exit $exitCode
    fi
}

# Verify that the prereq commands we need are installed
confirmcmds() {
    for c in $*; do
        #echo "checking $c..."
        if ! which $c >/dev/null; then
            echo "Error: $c is not installed but required, exiting"
            exit 2
        fi
    done
}

# Parses the voucher to get the UUID of the device (which will be our node id)
parseVoucher() {
    local voucherFile=$1
    local uuid=$(jq -r .oh.g $voucherFile | base64 -d | hexdump -v -e '/1 "%02x" ')
    chk $? 'parse voucher'
    echo "${uuid:0:8}-${uuid:8:4}-${uuid:12:4}-${uuid:16:4}-${uuid:20}"
}

# Main
confirmcmds jq base64 hexdump

deviceUuid=$(parseVoucher $voucherFile)
echo "Device UUID: $deviceUuid"
