#!/bin/bash

# Convenience script to simulate the owner booting a VM device

usage() {
    exitCode=${1:-0}
    cat << EndOfMessage
Usage: ${0##*/} [<edge-service-url>]

Arguments:
  <edge-service-url>  (Optional) Wait until this Horizon edge service starts.
EndOfMessage
    exit $exitCode
}

if [[ $1 == '-h' || $1 == '--help' ]]; then usage 0; fi

serviceUrl="$1"
#jsonFile=$2  #for testing
useNativeClient=${SDO_DEVICE_USE_NATIVE_CLIENT:-false}   # future: add cmd line flag for this too

#====================== Functions ======================

# Check the exit code passed in and exit if non-zero
chk() {
    local exitCode=$1
    local task=$2
    local dontExit=$3   # set to 'continue' to not exit for this error
    if [[ $exitCode == 0 ]]; then return; fi
    echo "Error: exit code $exitCode from: $task"
    if [[ $dontExit != 'continue' ]]; then
        exit $exitCode
    fi
}

# Check both the exit code and http code passed in and exit if non-zero
chkHttp() {
    local exitCode=$1
    local httpCode=$2
    local task=$3
    local dontExit=$4   # set to 'continue' to not exit for this error
    chk $exitCode $task
    if [[ $httpCode == 200 ]]; then return; fi
    echo "Error: http code $httpCode from: $task"
    if [[ $dontExit != 'continue' ]]; then
        exit $httpCode
    fi
}

# Verify that the prereq commands we need are installed
confirmcmds() {
    for c in $*; do
        #echo "checking $c..."
        if ! which $c >/dev/null; then
            echo "Error: $c is not installed but required, exiting"
            exit 2
        fi
    done
}

# Used when watch the agreements for serviceUrl. Returns 1 of: none, negotiating, started
getAgreementState() {
    local json=$(hzn agreement list)
    #local json=$(cat $jsonFile)  # for testing
    local agSvcUrls=$(jq -r '.[].workload_to_run.url' <<< $json)
    #echo "agSvcUrls=${agSvcUrls}."
    #if [[ $agSvcUrls != $serviceUrl ]]; then
    # Need to handle the case where there are multiple agreement. See if at least 1 is for this service
    if ! echo "$agSvcUrls" | grep -qw "$serviceUrl"; then
        echo 'none'
        return
    fi

    # We found at least a partial agreement for this service, so see how far along the agreement is
    #local exStartTime=$(jq -r '.[].agreement_execution_start_time' <<< $json)
    local exStartTime=$(jq -r '.[] | select(.workload_to_run.url=="'$serviceUrl'") | .agreement_execution_start_time' <<< $json)
    #echo "exStartTime=$exStartTime."
    if [[ -z $exStartTime ]]; then
        echo 'negotiating'
    else
        echo 'started'
    fi
}


#====================== Main Code ======================

confirmcmds jq

# If node is registered (if you have run this script before), then unregister it
if which hzn >/dev/null; then
    if [[ $(hzn node list 2>&1 | jq -r '.configstate.state' 2>&1) == 'configured' ]]; then
        hzn unregister -f
    fi
fi

# "Boot" device to have SDO get it registered with the management hub
deviceBinaryDir='sdo_device_binaries_1.8_linux_x64'
if [[ ! -d $deviceBinaryDir ]]; then
    deviceBinaryTar="$deviceBinaryDir.tar.gz"
    deviceBinaryUrl="https://github.com/open-horizon/SDO-support/releases/download/sdo_device_binaries_1.8/$deviceBinaryTar"
    echo "Getting and unpacking $deviceBinaryDir ..."
    httpCode=$(curl -w "%{http_code}" --progress-bar -L -O $deviceBinaryUrl)
    chkHttp $? $httpCode "getting $deviceBinaryTar"
    tar -zxvf $deviceBinaryTar
fi
if [[ $useNativeClient == 'true' ]]; then
    echo "Booting with native client..."
    if [[ $(whoami) != 'root' ]]; then
        echo "Error: must be root to the SDO native client"
        exit 2
    fi
    cd $deviceBinaryDir/SDOClientIntel/hostapp_linux
    ./sdo_to
    chk $? 'booting with sdo_to'
    cd ../../..
else
    echo "Booting with java client..."
    cd $deviceBinaryDir/device
    ./device
    chk $? 'booting with java device'
    cd ../..
fi

# If they didn't specify a serviceUrl agreement to watch for, then we are done
if [[ -z "$serviceUrl" ]]; then
    exit
fi

# Keep checking agreements and use a poor man's state machine to keep the user informed about the progress of the serviceUrl agreement
#prevState='started'  # for testing
interval=2
while true; do
    case $(getAgreementState) in
        none)
            if [[ -z $prevState ]]; then printf "Waiting for agreement for $serviceUrl "   # very beginning
            elif [[ $prevState == 'none' ]]; then printf '.'
            else printf "\nAgreement cancelled. Waiting again for agreement for $serviceUrl "
            fi
            prevState='none'
            ;;
        negotiating)
            if [[ -z $prevState || $prevState == 'none' ]]; then printf "\nAgreement negotiation for $serviceUrl started. Waiting for completion "
            elif [[ $prevState == 'negotiating' ]]; then printf '.'
            else printf "\nAgreement cancelled. Agreement negotiation for $serviceUrl started. Waiting for completion "
            fi
            prevState='negotiating'
            ;;
        started)
            printf "\nAgreement negotiation completed and $serviceUrl is started.\n"
            break
            ;;
        esac
    sleep $interval
done

# We only get here if the agreement for serviceUrl was finished (service executing)
echo "To see the service log: hzn service log -f $serviceUrl"

